/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: yarn_spinner.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "yarn_spinner.pb-c.h"
void   yarn__program__nodes_entry__init
                     (Yarn__Program__NodesEntry         *message)
{
  static const Yarn__Program__NodesEntry init_value = YARN__PROGRAM__NODES_ENTRY__INIT;
  *message = init_value;
}
void   yarn__program__initial_values_entry__init
                     (Yarn__Program__InitialValuesEntry         *message)
{
  static const Yarn__Program__InitialValuesEntry init_value = YARN__PROGRAM__INITIAL_VALUES_ENTRY__INIT;
  *message = init_value;
}
void   yarn__program__init
                     (Yarn__Program         *message)
{
  static const Yarn__Program init_value = YARN__PROGRAM__INIT;
  *message = init_value;
}
size_t yarn__program__get_packed_size
                     (const Yarn__Program *message)
{
  assert(message->base.descriptor == &yarn__program__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yarn__program__pack
                     (const Yarn__Program *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yarn__program__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yarn__program__pack_to_buffer
                     (const Yarn__Program *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yarn__program__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yarn__Program *
       yarn__program__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yarn__Program *)
     protobuf_c_message_unpack (&yarn__program__descriptor,
                                allocator, len, data);
}
void   yarn__program__free_unpacked
                     (Yarn__Program *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yarn__program__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yarn__node__labels_entry__init
                     (Yarn__Node__LabelsEntry         *message)
{
  static const Yarn__Node__LabelsEntry init_value = YARN__NODE__LABELS_ENTRY__INIT;
  *message = init_value;
}
void   yarn__node__init
                     (Yarn__Node         *message)
{
  static const Yarn__Node init_value = YARN__NODE__INIT;
  *message = init_value;
}
size_t yarn__node__get_packed_size
                     (const Yarn__Node *message)
{
  assert(message->base.descriptor == &yarn__node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yarn__node__pack
                     (const Yarn__Node *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yarn__node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yarn__node__pack_to_buffer
                     (const Yarn__Node *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yarn__node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yarn__Node *
       yarn__node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yarn__Node *)
     protobuf_c_message_unpack (&yarn__node__descriptor,
                                allocator, len, data);
}
void   yarn__node__free_unpacked
                     (Yarn__Node *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yarn__node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yarn__instruction__init
                     (Yarn__Instruction         *message)
{
  static const Yarn__Instruction init_value = YARN__INSTRUCTION__INIT;
  *message = init_value;
}
size_t yarn__instruction__get_packed_size
                     (const Yarn__Instruction *message)
{
  assert(message->base.descriptor == &yarn__instruction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yarn__instruction__pack
                     (const Yarn__Instruction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yarn__instruction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yarn__instruction__pack_to_buffer
                     (const Yarn__Instruction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yarn__instruction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yarn__Instruction *
       yarn__instruction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yarn__Instruction *)
     protobuf_c_message_unpack (&yarn__instruction__descriptor,
                                allocator, len, data);
}
void   yarn__instruction__free_unpacked
                     (Yarn__Instruction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yarn__instruction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   yarn__operand__init
                     (Yarn__Operand         *message)
{
  static const Yarn__Operand init_value = YARN__OPERAND__INIT;
  *message = init_value;
}
size_t yarn__operand__get_packed_size
                     (const Yarn__Operand *message)
{
  assert(message->base.descriptor == &yarn__operand__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t yarn__operand__pack
                     (const Yarn__Operand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &yarn__operand__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t yarn__operand__pack_to_buffer
                     (const Yarn__Operand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &yarn__operand__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Yarn__Operand *
       yarn__operand__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Yarn__Operand *)
     protobuf_c_message_unpack (&yarn__operand__descriptor,
                                allocator, len, data);
}
void   yarn__operand__free_unpacked
                     (Yarn__Operand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &yarn__operand__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor yarn__program__nodes_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yarn__Program__NodesEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yarn__Program__NodesEntry, value),
    &yarn__node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yarn__program__nodes_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange yarn__program__nodes_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yarn__program__nodes_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Yarn.Program.NodesEntry",
  "NodesEntry",
  "Yarn__Program__NodesEntry",
  "Yarn",
  sizeof(Yarn__Program__NodesEntry),
  2,
  yarn__program__nodes_entry__field_descriptors,
  yarn__program__nodes_entry__field_indices_by_name,
  1,  yarn__program__nodes_entry__number_ranges,
  (ProtobufCMessageInit) yarn__program__nodes_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yarn__program__initial_values_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yarn__Program__InitialValuesEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Yarn__Program__InitialValuesEntry, value),
    &yarn__operand__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yarn__program__initial_values_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange yarn__program__initial_values_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yarn__program__initial_values_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Yarn.Program.InitialValuesEntry",
  "InitialValuesEntry",
  "Yarn__Program__InitialValuesEntry",
  "Yarn",
  sizeof(Yarn__Program__InitialValuesEntry),
  2,
  yarn__program__initial_values_entry__field_descriptors,
  yarn__program__initial_values_entry__field_indices_by_name,
  1,  yarn__program__initial_values_entry__number_ranges,
  (ProtobufCMessageInit) yarn__program__initial_values_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yarn__program__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yarn__Program, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yarn__Program, n_nodes),
    offsetof(Yarn__Program, nodes),
    &yarn__program__nodes_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initial_values",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yarn__Program, n_initial_values),
    offsetof(Yarn__Program, initial_values),
    &yarn__program__initial_values_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yarn__program__field_indices_by_name[] = {
  2,   /* field[2] = initial_values */
  0,   /* field[0] = name */
  1,   /* field[1] = nodes */
};
static const ProtobufCIntRange yarn__program__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yarn__program__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Yarn.Program",
  "Program",
  "Yarn__Program",
  "Yarn",
  sizeof(Yarn__Program),
  3,
  yarn__program__field_descriptors,
  yarn__program__field_indices_by_name,
  1,  yarn__program__number_ranges,
  (ProtobufCMessageInit) yarn__program__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yarn__node__labels_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yarn__Node__LabelsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Yarn__Node__LabelsEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yarn__node__labels_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange yarn__node__labels_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yarn__node__labels_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Yarn.Node.LabelsEntry",
  "LabelsEntry",
  "Yarn__Node__LabelsEntry",
  "Yarn",
  sizeof(Yarn__Node__LabelsEntry),
  2,
  yarn__node__labels_entry__field_descriptors,
  yarn__node__labels_entry__field_indices_by_name,
  1,  yarn__node__labels_entry__number_ranges,
  (ProtobufCMessageInit) yarn__node__labels_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yarn__node__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yarn__Node, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instructions",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yarn__Node, n_instructions),
    offsetof(Yarn__Node, instructions),
    &yarn__instruction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "labels",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yarn__Node, n_labels),
    offsetof(Yarn__Node, labels),
    &yarn__node__labels_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yarn__Node, n_tags),
    offsetof(Yarn__Node, tags),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sourceTextStringID",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Yarn__Node, sourcetextstringid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yarn__node__field_indices_by_name[] = {
  1,   /* field[1] = instructions */
  2,   /* field[2] = labels */
  0,   /* field[0] = name */
  4,   /* field[4] = sourceTextStringID */
  3,   /* field[3] = tags */
};
static const ProtobufCIntRange yarn__node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor yarn__node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Yarn.Node",
  "Node",
  "Yarn__Node",
  "Yarn",
  sizeof(Yarn__Node),
  5,
  yarn__node__field_descriptors,
  yarn__node__field_indices_by_name,
  1,  yarn__node__number_ranges,
  (ProtobufCMessageInit) yarn__node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue yarn__instruction__op_code__enum_values_by_number[17] =
{
  { "JUMP_TO", "YARN__INSTRUCTION__OP_CODE__JUMP_TO", 0 },
  { "JUMP", "YARN__INSTRUCTION__OP_CODE__JUMP", 1 },
  { "RUN_LINE", "YARN__INSTRUCTION__OP_CODE__RUN_LINE", 2 },
  { "RUN_COMMAND", "YARN__INSTRUCTION__OP_CODE__RUN_COMMAND", 3 },
  { "ADD_OPTION", "YARN__INSTRUCTION__OP_CODE__ADD_OPTION", 4 },
  { "SHOW_OPTIONS", "YARN__INSTRUCTION__OP_CODE__SHOW_OPTIONS", 5 },
  { "PUSH_STRING", "YARN__INSTRUCTION__OP_CODE__PUSH_STRING", 6 },
  { "PUSH_FLOAT", "YARN__INSTRUCTION__OP_CODE__PUSH_FLOAT", 7 },
  { "PUSH_BOOL", "YARN__INSTRUCTION__OP_CODE__PUSH_BOOL", 8 },
  { "PUSH_NULL", "YARN__INSTRUCTION__OP_CODE__PUSH_NULL", 9 },
  { "JUMP_IF_FALSE", "YARN__INSTRUCTION__OP_CODE__JUMP_IF_FALSE", 10 },
  { "POP", "YARN__INSTRUCTION__OP_CODE__POP", 11 },
  { "CALL_FUNC", "YARN__INSTRUCTION__OP_CODE__CALL_FUNC", 12 },
  { "PUSH_VARIABLE", "YARN__INSTRUCTION__OP_CODE__PUSH_VARIABLE", 13 },
  { "STORE_VARIABLE", "YARN__INSTRUCTION__OP_CODE__STORE_VARIABLE", 14 },
  { "STOP", "YARN__INSTRUCTION__OP_CODE__STOP", 15 },
  { "RUN_NODE", "YARN__INSTRUCTION__OP_CODE__RUN_NODE", 16 },
};
static const ProtobufCIntRange yarn__instruction__op_code__value_ranges[] = {
{0, 0},{0, 17}
};
static const ProtobufCEnumValueIndex yarn__instruction__op_code__enum_values_by_name[17] =
{
  { "ADD_OPTION", 4 },
  { "CALL_FUNC", 12 },
  { "JUMP", 1 },
  { "JUMP_IF_FALSE", 10 },
  { "JUMP_TO", 0 },
  { "POP", 11 },
  { "PUSH_BOOL", 8 },
  { "PUSH_FLOAT", 7 },
  { "PUSH_NULL", 9 },
  { "PUSH_STRING", 6 },
  { "PUSH_VARIABLE", 13 },
  { "RUN_COMMAND", 3 },
  { "RUN_LINE", 2 },
  { "RUN_NODE", 16 },
  { "SHOW_OPTIONS", 5 },
  { "STOP", 15 },
  { "STORE_VARIABLE", 14 },
};
const ProtobufCEnumDescriptor yarn__instruction__op_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Yarn.Instruction.OpCode",
  "OpCode",
  "Yarn__Instruction__OpCode",
  "Yarn",
  17,
  yarn__instruction__op_code__enum_values_by_number,
  17,
  yarn__instruction__op_code__enum_values_by_name,
  1,
  yarn__instruction__op_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor yarn__instruction__field_descriptors[2] =
{
  {
    "opcode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Yarn__Instruction, opcode),
    &yarn__instruction__op_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operands",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Yarn__Instruction, n_operands),
    offsetof(Yarn__Instruction, operands),
    &yarn__operand__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yarn__instruction__field_indices_by_name[] = {
  0,   /* field[0] = opcode */
  1,   /* field[1] = operands */
};
static const ProtobufCIntRange yarn__instruction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor yarn__instruction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Yarn.Instruction",
  "Instruction",
  "Yarn__Instruction",
  "Yarn",
  sizeof(Yarn__Instruction),
  2,
  yarn__instruction__field_descriptors,
  yarn__instruction__field_indices_by_name,
  1,  yarn__instruction__number_ranges,
  (ProtobufCMessageInit) yarn__instruction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor yarn__operand__field_descriptors[3] =
{
  {
    "string_value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Yarn__Operand, value_case),
    offsetof(Yarn__Operand, string_value),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Yarn__Operand, value_case),
    offsetof(Yarn__Operand, bool_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Yarn__Operand, value_case),
    offsetof(Yarn__Operand, float_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned yarn__operand__field_indices_by_name[] = {
  1,   /* field[1] = bool_value */
  2,   /* field[2] = float_value */
  0,   /* field[0] = string_value */
};
static const ProtobufCIntRange yarn__operand__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor yarn__operand__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Yarn.Operand",
  "Operand",
  "Yarn__Operand",
  "Yarn",
  sizeof(Yarn__Operand),
  3,
  yarn__operand__field_descriptors,
  yarn__operand__field_indices_by_name,
  1,  yarn__operand__number_ranges,
  (ProtobufCMessageInit) yarn__operand__init,
  NULL,NULL,NULL    /* reserved[123] */
};
